global:
  scrape_interval: 15s

scrape_configs:
  -
    job_name: 'telegraf'
    static_configs:
      - targets: 
          - 'telegraf:9273'
  -
    job_name: 'postgres'
    static_configs:
      - targets: 
          - 'postgres-exporter:9187'
