volumes:
  activemq-data: {}
  postgres-data: {}

services:
  activemq-broker:
    hostname: activemq-broker
    restart: unless-stopped
    build:
      context: ../docker/
      dockerfile: Dockerfile.debian
    depends_on:
      - postgres
    environment:
      ADMIN_USERNAME: system
      ADMIN_PASSWORD: manager
    volumes:
      - activemq-data:/opt/activemq/data:rw
      - ./activemq/activemq.postgres.xml:/opt/activemq/conf/activemq.xml:ro
      - ./activemq/postgres.properties:/opt/activemq/conf/postgres.properties:ro
    ports: ["8161:8161"]
  
  postgres:
    image: postgres:alpine
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: activemq
      PGDATA: /var/lib/postgresql/dat/activemq
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    hostname: postgres-exporter
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATA_SOURCE_URI: "postgres:5432/activemq?sslmode=disable"
      DATA_SOURCE_USER: postgres
      DATA_SOURCE_PASS: postgres 
    command: # See https://github.com/prometheus-community/postgres_exporter?tab=readme-ov-file#flags
      - '--web.telemetry-path=/metrics'
      - '--disable-default-metrics'
      - '--disable-settings-metrics'
      - '--collector.database'
